import { siteConfig } from "@/config/site";

export const MOCK = [
  {
    id: "1",
    title: "2-Bedroom Apartment in Lekki Phase 1",
    slug: "2-bedroom-apartment-lekki",
    price: 250000,
    purpose: "rent",
    status: "available",
    verified: true,
    type: "2-bedroom-flat",
    category: "residential",
    address: "12 Admiralty Way, Lekki Phase 1",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 2,
    baths: 2,
    size: 110,
    kitchen_available: true,
    kitchen_type: "modern",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 2,
    amenities: ["parking", "security", "water heater", "balcony"],
    description:
      "Spacious 2-bedroom apartment with modern kitchen, ample parking, and 24-hour security.",
    images: [siteConfig.logo, siteConfig.logo, siteConfig.logo],
    lat: 6.4321,
    lng: 3.45,
    landlord_id: "user-1",
    agent_id: "agent-1",
    views: 25,
    favorites: 5,
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2025-11-02T14:00:00Z",
  },
  {
    id: "2",
    title: "1 Room Self Contain, Yaba",
    slug: "1-room-self-contain-yaba",
    price: 40000,
    purpose: "rent",
    status: "available",
    verified: false,
    type: "self-contain",
    category: "residential",
    address: "32 Commercial Ave, Yaba",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 1,
    baths: 1,
    size: 45,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: true,
    toilet_type: "shared",
    floor_level: 1,
    amenities: ["borehole", "gated compound"],
    description:
      "Affordable single-room self-contain located close to Unilag, suitable for students or young professionals.",
    images: [siteConfig.logo],
    lat: 6.5173,
    lng: 3.384,
    landlord_id: "user-2",
    agent_id: "agent-2",
    views: 10,
    favorites: 2,
    created_at: "2025-11-02T12:30:00Z",
    updated_at: "2025-11-03T09:00:00Z",
  },
  {
    id: "3",
    title: "3 Bedroom Duplex, Ikeja GRA",
    slug: "3-bedroom-duplex-ikeja",
    price: 600000,
    purpose: "rent",
    status: "occupied",
    verified: true,
    type: "duplex",
    category: "residential",
    address: "8B Isaac John Street, Ikeja GRA",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 3,
    baths: 3,
    size: 210,
    kitchen_available: true,
    kitchen_type: "standard",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 2,
    amenities: [
      "fenced compound",
      "CCTV",
      "standby generator",
      "wardrobes",
      "intercom",
    ],
    description:
      "Fully serviced 3-bedroom duplex in a gated estate with backup power and modern security features.",
    images: [siteConfig.logo, siteConfig.logo, siteConfig.logo],
    lat: 6.6018,
    lng: 3.3515,
    landlord_id: "user-3",
    agent_id: "agent-3",
    views: 47,
    favorites: 9,
    created_at: "2025-11-03T09:45:00Z",
    updated_at: "2025-11-04T08:20:00Z",
  },
  {
    id: "4",
    title: "Office Space for Lease, Victoria Island",
    slug: "office-space-victoria-island",
    price: 850000,
    purpose: "lease",
    status: "available",
    verified: true,
    type: "office-space",
    category: "commercial",
    address: "10 Adeola Odeku, Victoria Island",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 0,
    baths: 2,
    size: 320,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: true,
    toilet_type: "public",
    floor_level: 3,
    amenities: [
      "elevator",
      "parking lot",
      "24hr electricity",
      "CCTV",
      "reception",
    ],
    description:
      "Modern office space suitable for startups and agencies. Located in the heart of Victoria Island.",
    images: [siteConfig.logo],
    lat: 6.4282,
    lng: 3.4219,
    landlord_id: "user-4",
    agent_id: "agent-4",
    views: 19,
    favorites: 3,
    created_at: "2025-11-04T10:00:00Z",
    updated_at: "2025-11-04T10:00:00Z",
  },
  {
    id: "5",
    title: "Mini Flat, Surulere",
    slug: "mini-flat-surulere",
    price: 120000,
    purpose: "rent",
    status: "available",
    verified: true,
    type: "mini-flat",
    category: "residential",
    address: "7 Bode Thomas Street, Surulere",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 1,
    baths: 1,
    size: 75,
    kitchen_available: true,
    kitchen_type: "standard",
    toilet_available: true,
    toilet_type: "standard",
    floor_level: 1,
    amenities: ["water supply", "wardrobe", "balcony"],
    description: "Mini flat in a serene environment close to major roads.",
    images: [siteConfig.logo],
    lat: 6.495,
    lng: 3.345,
    landlord_id: "user-5",
    agent_id: "agent-5",
    views: 13,
    favorites: 1,
    created_at: "2025-11-04T11:00:00Z",
    updated_at: "2025-11-04T11:00:00Z",
  },
  {
    id: "6",
    title: "4-Bedroom Duplex, Asokoro",
    slug: "4-bedroom-duplex-asokoro",
    price: 1200000,
    purpose: "rent",
    status: "available",
    verified: true,
    type: "duplex",
    category: "residential",
    address: "23 Kwame Nkrumah St, Asokoro",
    city: "Abuja",
    state: "FCT",
    country: "Nigeria",
    beds: 4,
    baths: 4,
    size: 400,
    kitchen_available: true,
    kitchen_type: "standard",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 2,
    amenities: ["security post", "parking", "generator"],
    description:
      "Elegant 4-bedroom duplex in Asokoro with ample parking and reliable electricity.",
    images: [siteConfig.logo],
    lat: 9.04,
    lng: 7.51,
    landlord_id: "user-6",
    agent_id: "agent-6",
    views: 32,
    favorites: 6,
    created_at: "2025-11-04T11:30:00Z",
    updated_at: "2025-11-04T11:30:00Z",
  },
  {
    id: "7",
    title: "Luxury 3-Bedroom Apartment, Banana Island",
    slug: "3-bedroom-apartment-banana-island",
    price: 2500000,
    purpose: "rent",
    status: "available",
    verified: true,
    type: "luxury-apartment",
    category: "residential",
    address: "Block 5, Banana Island, Ikoyi",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 3,
    baths: 3,
    size: 300,
    kitchen_available: true,
    kitchen_type: "modern",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 5,
    amenities: ["swimming pool", "gym", "CCTV", "elevator"],
    description:
      "High-end apartment with stunning waterfront views and modern facilities.",
    images: [siteConfig.logo],
    lat: 6.447,
    lng: 3.423,
    landlord_id: "user-7",
    agent_id: "agent-7",
    views: 102,
    favorites: 25,
    created_at: "2025-11-04T12:00:00Z",
    updated_at: "2025-11-04T12:00:00Z",
  },
  {
    id: "8",
    title: "Shop Space, Wuse Market",
    slug: "shop-space-wuse",
    price: 180000,
    purpose: "lease",
    status: "available",
    verified: false,
    type: "shop",
    category: "commercial",
    address: "Wuse Market, Zone 5",
    city: "Abuja",
    state: "FCT",
    country: "Nigeria",
    beds: 0,
    baths: 1,
    size: 30,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: false,
    toilet_type: "none",
    floor_level: 1,
    amenities: ["parking", "security"],
    description:
      "Affordable retail space in the busy Wuse Market, ideal for small business owners.",
    images: [siteConfig.logo],
    lat: 9.07,
    lng: 7.48,
    landlord_id: "user-8",
    agent_id: "agent-8",
    views: 20,
    favorites: 3,
    created_at: "2025-11-04T12:10:00Z",
    updated_at: "2025-11-04T12:10:00Z",
  },
  {
    id: "9",
    title: "Land for Sale, Ibeju-Lekki",
    slug: "land-for-sale-ibeju-lekki",
    price: 1500000,
    purpose: "sale",
    status: "available",
    verified: true,
    type: "land",
    category: "land",
    address: "Eleranigbe, Ibeju-Lekki",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 0,
    baths: 0,
    size: 600,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: false,
    toilet_type: "none",
    floor_level: 0,
    amenities: ["dry land", "fenced", "survey plan"],
    description: "Dry fenced plot suitable for residential or commercial use.",
    images: [siteConfig.logo],
    lat: 6.45,
    lng: 3.67,
    landlord_id: "user-9",
    agent_id: "agent-9",
    views: 55,
    favorites: 7,
    created_at: "2025-11-04T12:30:00Z",
    updated_at: "2025-11-04T12:30:00Z",
  },
  {
    id: "10",
    title: "Warehouse, Apapa",
    slug: "warehouse-apapa",
    price: 750000,
    purpose: "lease",
    status: "available",
    verified: true,
    type: "warehouse",
    category: "commercial",
    address: "Creek Road, Apapa",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 0,
    baths: 2,
    size: 1200,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: true,
    toilet_type: "public",
    floor_level: 1,
    amenities: ["truck access", "security", "parking"],
    description:
      "Spacious warehouse suitable for logistics, import, and export operations.",
    images: [siteConfig.logo],
    lat: 6.44,
    lng: 3.37,
    landlord_id: "user-10",
    agent_id: "agent-10",
    views: 33,
    favorites: 4,
    created_at: "2025-11-04T12:50:00Z",
    updated_at: "2025-11-04T12:50:00Z",
  },
  {
    id: "11",
    title: "3-Bedroom Flat, Enugu GRA",
    slug: "3-bedroom-flat-enugu-gra",
    price: 300000,
    purpose: "rent",
    status: "available",
    verified: true,
    type: "flat",
    category: "residential",
    address: "14 Ridgeway Street, Enugu GRA",
    city: "Enugu",
    state: "Enugu",
    country: "Nigeria",
    beds: 3,
    baths: 3,
    size: 180,
    kitchen_available: true,
    kitchen_type: "standard",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 2,
    amenities: ["security", "water supply", "balcony"],
    description: "Clean 3-bedroom flat in a calm neighborhood in Enugu GRA.",
    images: [siteConfig.logo],
    lat: 6.45,
    lng: 7.5,
    landlord_id: "user-11",
    agent_id: "agent-11",
    views: 17,
    favorites: 2,
    created_at: "2025-11-04T13:00:00Z",
    updated_at: "2025-11-04T13:00:00Z",
  },
  {
    id: "12",
    title: "2-Bedroom Apartment, Port Harcourt",
    slug: "2-bedroom-apartment-ph",
    price: 220000,
    purpose: "rent",
    status: "available",
    verified: true,
    type: "flat",
    category: "residential",
    address: "45 Aba Road, Port Harcourt",
    city: "Port Harcourt",
    state: "Rivers",
    country: "Nigeria",
    beds: 2,
    baths: 2,
    size: 130,
    kitchen_available: true,
    kitchen_type: "standard",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 2,
    amenities: ["fenced compound", "parking", "CCTV"],
    description:
      "Newly built 2-bedroom apartment with modern interior and 24/7 power.",
    images: [siteConfig.logo],
    lat: 4.82,
    lng: 7.03,
    landlord_id: "user-12",
    agent_id: "agent-12",
    views: 21,
    favorites: 4,
    created_at: "2025-11-04T13:20:00Z",
    updated_at: "2025-11-04T13:20:00Z",
  },
  {
    id: "13",
    title: "Land for Sale, Awka",
    slug: "land-for-sale-awka",
    price: 1000000,
    purpose: "sale",
    status: "available",
    verified: true,
    type: "land",
    category: "land",
    address: "Isiagu Layout, Awka South",
    city: "Awka",
    state: "Anambra",
    country: "Nigeria",
    beds: 0,
    baths: 0,
    size: 500,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: false,
    toilet_type: "none",
    floor_level: 0,
    amenities: ["survey plan", "dry land"],
    description:
      "Registered dry plot close to the state secretariat, ideal for residential building.",
    images: [siteConfig.logo],
    lat: 6.22,
    lng: 7.07,
    landlord_id: "user-13",
    agent_id: "agent-13",
    views: 14,
    favorites: 1,
    created_at: "2025-11-04T13:30:00Z",
    updated_at: "2025-11-04T13:30:00Z",
  },
  {
    id: "14",
    title: "Hotel Building for Sale, Owerri",
    slug: "hotel-for-sale-owerri",
    price: 9500000,
    purpose: "sale",
    status: "available",
    verified: true,
    type: "commercial-building",
    category: "commercial",
    address: "Along Port Harcourt Road, Owerri",
    city: "Owerri",
    state: "Imo",
    country: "Nigeria",
    beds: 15,
    baths: 18,
    size: 1200,
    kitchen_available: true,
    kitchen_type: "standard",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 5,
    amenities: ["bar", "parking", "borehole"],
    description: "15-room functional hotel with steady clientele base.",
    images: [siteConfig.logo],
    lat: 5.48,
    lng: 7.03,
    landlord_id: "user-14",
    agent_id: "agent-14",
    views: 60,
    favorites: 8,
    created_at: "2025-11-04T13:45:00Z",
    updated_at: "2025-11-04T13:45:00Z",
  },
  {
    id: "15",
    title: "Office Complex, Kaduna North",
    slug: "office-complex-kaduna",
    price: 700000,
    purpose: "lease",
    status: "available",
    verified: false,
    type: "office-complex",
    category: "commercial",
    address: "Independence Way, Kaduna North",
    city: "Kaduna",
    state: "Kaduna",
    country: "Nigeria",
    beds: 0,
    baths: 4,
    size: 600,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: true,
    toilet_type: "public",
    floor_level: 3,
    amenities: ["parking lot", "standby power"],
    description:
      "Office space suitable for NGOs and firms, central business district location.",
    images: [siteConfig.logo],
    lat: 10.52,
    lng: 7.44,
    landlord_id: "user-15",
    agent_id: "agent-15",
    views: 26,
    favorites: 3,
    created_at: "2025-11-04T14:00:00Z",
    updated_at: "2025-11-04T14:00:00Z",
  },
  {
    id: "16",
    title: "Luxury Bungalow, Abeokuta",
    slug: "luxury-bungalow-abeokuta",
    price: 550000,
    purpose: "sale",
    status: "available",
    verified: true,
    type: "bungalow",
    category: "residential",
    address: "Obasanjo Hilltop Estate, Abeokuta",
    city: "Abeokuta",
    state: "Ogun",
    country: "Nigeria",
    beds: 4,
    baths: 4,
    size: 350,
    kitchen_available: true,
    kitchen_type: "modern",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 1,
    amenities: ["fenced compound", "CCTV", "borehole"],
    description:
      "Tastefully finished 4-bedroom bungalow in a serene gated estate.",
    images: [siteConfig.logo],
    lat: 7.16,
    lng: 3.35,
    landlord_id: "user-16",
    agent_id: "agent-16",
    views: 37,
    favorites: 6,
    created_at: "2025-11-04T14:20:00Z",
    updated_at: "2025-11-04T14:20:00Z",
  },
  {
    id: "17",
    title: "2-Bedroom Flat, Ibadan",
    slug: "2-bedroom-flat-ibadan",
    price: 180000,
    purpose: "rent",
    status: "available",
    verified: true,
    type: "flat",
    category: "residential",
    address: "Ring Road, Ibadan",
    city: "Ibadan",
    state: "Oyo",
    country: "Nigeria",
    beds: 2,
    baths: 2,
    size: 150,
    kitchen_available: true,
    kitchen_type: "standard",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 2,
    amenities: ["fenced", "parking"],
    description:
      "Modern 2-bedroom flat located close to major amenities and road access.",
    images: [siteConfig.logo],
    lat: 7.37,
    lng: 3.92,
    landlord_id: "user-17",
    agent_id: "agent-17",
    views: 18,
    favorites: 3,
    created_at: "2025-11-04T14:40:00Z",
    updated_at: "2025-11-04T14:40:00Z",
  },
  {
    id: "18",
    title: "Shop for Rent, Onitsha Main Market",
    slug: "shop-rent-onitsha",
    price: 90000,
    purpose: "rent",
    status: "available",
    verified: false,
    type: "shop",
    category: "commercial",
    address: "Main Market, Onitsha",
    city: "Onitsha",
    state: "Anambra",
    country: "Nigeria",
    beds: 0,
    baths: 0,
    size: 25,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: false,
    toilet_type: "none",
    floor_level: 1,
    amenities: ["parking", "security"],
    description:
      "Affordable shop space at Onitsha Main Market, good for traders.",
    images: [siteConfig.logo],
    lat: 6.15,
    lng: 6.79,
    landlord_id: "user-18",
    agent_id: "agent-18",
    views: 29,
    favorites: 4,
    created_at: "2025-11-04T15:00:00Z",
    updated_at: "2025-11-04T15:00:00Z",
  },
  {
    id: "19",
    title: "Event Hall, Uyo",
    slug: "event-hall-uyo",
    price: 450000,
    purpose: "lease",
    status: "available",
    verified: true,
    type: "event-hall",
    category: "commercial",
    address: "Ibom Plaza, Uyo",
    city: "Uyo",
    state: "Akwa Ibom",
    country: "Nigeria",
    beds: 0,
    baths: 2,
    size: 800,
    kitchen_available: false,
    kitchen_type: "none",
    toilet_available: true,
    toilet_type: "public",
    floor_level: 1,
    amenities: ["parking", "soundproofing", "air conditioning"],
    description:
      "Spacious event center ideal for weddings and corporate events.",
    images: [siteConfig.logo],
    lat: 5.03,
    lng: 7.93,
    landlord_id: "user-19",
    agent_id: "agent-19",
    views: 42,
    favorites: 8,
    created_at: "2025-11-04T15:10:00Z",
    updated_at: "2025-11-04T15:10:00Z",
  },
  {
    id: "20",
    title: "1-Bedroom Shortlet, Lekki",
    slug: "1-bedroom-shortlet-lekki",
    price: 65000,
    purpose: "shortlet",
    status: "available",
    verified: true,
    type: "shortlet",
    category: "residential",
    address: "Lekki Phase 2",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    beds: 1,
    baths: 1,
    size: 80,
    kitchen_available: true,
    kitchen_type: "modern",
    toilet_available: true,
    toilet_type: "ensuite",
    floor_level: 1,
    amenities: ["wifi", "security", "smart TV"],
    description:
      "Fully furnished 1-bedroom shortlet with Wi-Fi and 24hr light.",
    images: [siteConfig.logo],
    lat: 6.43,
    lng: 3.54,
    landlord_id: "user-20",
    agent_id: "agent-20",
    views: 67,
    favorites: 10,
    created_at: "2025-11-04T15:30:00Z",
    updated_at: "2025-11-04T15:30:00Z",
  },
];
