import Link from "next/link";
import { ArrowUpRight, Clock3, ShieldCheck } from "lucide-react";

type LinkedRow = Record<string, unknown> & { id?: string };
type Detail = Record<string, unknown>;

const label = (value: string) => value.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/^./, (letter) => letter.toUpperCase());
const text = (value: unknown) => value instanceof Date ? value.toLocaleString("en-NG") : Array.isArray(value) ? value.join(", ") || "None" : value === null || value === undefined || value === "" ? "Not recorded" : typeof value === "boolean" ? value ? "Yes" : "No" : String(value);
const hrefFor = (kind: string, row: LinkedRow) => { const id = row.id; if (!id) return null; if (kind === "properties") return `/admin/properties?item=${id}`; if (kind === "payments") return `/admin/payments?item=${id}`; if (kind === "verificationSubmissions") return `/admin/verifications?item=${id}`; return null; };

export function AdminLinkedDetail({ kind, detail }: { kind: "user" | "property" | "payment" | "audit"; detail: Detail | null }) {
  if (!detail) return <section className="grid min-h-48 place-items-center border border-dashed border-line bg-white p-8 text-center"><div><ShieldCheck className="mx-auto size-7 text-muted" /><p className="mt-3 text-sm font-bold">Select a record to inspect</p><p className="mt-1 text-xs text-muted">Linked context is fetched only for the selected record.</p></div></section>;
  const reserved = new Set(["id", "firstName", "lastName", "title", "subject", "reference", "actor", "previousState", "resultingState", "relatedHref", "tenantProfile", "landlordProfile", "verificationSubmissions", "properties", "applications", "tenantLeases", "landlordLeases", "payments", "maintenance", "supportTickets", "auditEvents", "owner", "reviewedBy", "viewings", "leases", "disputes", "history", "leaseScheduleItem", "tenant", "property", "images", "amenities", "houseRules"]);
  const heading = kind === "user" ? `${text(detail.firstName)} ${text(detail.lastName)}` : text(detail.title ?? detail.reference ?? detail.action);
  const linkedKeys = Object.keys(detail).filter((key) => Array.isArray(detail[key]) && !["images", "amenities", "houseRules"].includes(key));
  return <section className="min-w-0 border border-line bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-line pb-5"><div className="min-w-0"><p className="text-xs font-bold text-forest-700">{label(kind)} detail</p><h2 className="mt-1 break-words text-2xl font-extrabold tracking-[-0.025em] text-ink">{heading}</h2></div>{typeof detail.relatedHref === "string" ? <Link href={detail.relatedHref} className="stitch-button-secondary">Open related record<ArrowUpRight className="size-4" /></Link> : null}</div>
    {kind === "audit" ? <div className="grid gap-5 py-5 lg:grid-cols-2"><State title="Previous state" value={detail.previousState} /><State title="Resulting state" value={detail.resultingState} /></div> : null}
    <dl className="grid gap-x-6 gap-y-4 py-5 sm:grid-cols-2 xl:grid-cols-3">{Object.entries(detail).filter(([key, value]) => !reserved.has(key) && typeof value !== "object").map(([key, value]) => <div key={key} className="min-w-0"><dt className="text-[11px] font-bold text-muted">{label(key)}</dt><dd className="mt-1 break-words text-sm font-bold text-ink">{text(value)}</dd></div>)}</dl>
    {kind === "user" ? <h3 className="border-t border-line pt-5 text-sm font-extrabold text-ink">Linked records</h3> : null}
    {linkedKeys.map((key) => <LinkedList key={key} title={key === "verificationSubmissions" ? "Verification history" : label(key)} kind={key} rows={detail[key] as LinkedRow[]} />)}
    {kind === "property" ? <><ObjectFacts title="Owner" value={detail.owner} /><ObjectFacts title="Publication and moderation" value={{ status: detail.status, moderationStatus: detail.moderationStatus, moderationReason: detail.moderationReason, verified: detail.verified, featured: detail.featured, reviewedAt: detail.reviewedAt }} /><ObjectFacts title="Fees" value={{ price: detail.price, period: detail.period, cautionFee: detail.cautionFee, legalFee: detail.legalFee, agencyFee: detail.agencyFee, serviceCharge: detail.serviceCharge }} /><ObjectFacts title="Media" value={{ images: detail.images, amenities: detail.amenities, houseRules: detail.houseRules }} /></> : null}
    {kind === "payment" ? <><ObjectFacts title="Tenant" value={detail.tenant} /><ObjectFacts title="Property" value={detail.property} /><ObjectFacts title="Lease schedule" value={detail.leaseScheduleItem} /><p className="border-t border-line pt-5 text-xs font-bold text-muted">Provider-controlled record · read only</p></> : null}
  </section>;
}

function LinkedList({ title, kind, rows }: { title: string; kind: string; rows: LinkedRow[] }) { return <section className="mt-5 border-t border-line pt-5"><h3 className="text-sm font-extrabold text-ink">{title} <span className="text-muted">({rows.length})</span></h3>{rows.length ? <div className="mt-3 divide-y divide-line border border-line">{rows.map((row, index) => { const href = hrefFor(kind, row); const propertyTitle = row.property && typeof row.property === "object" ? (row.property as LinkedRow).title : undefined; const content = <><strong className="break-words text-sm text-ink">{text(row.title ?? row.subject ?? row.reference ?? row.action ?? propertyTitle ?? `Record ${index + 1}`)}</strong><span className="mt-1 block text-xs text-muted">{text(row.status ?? row.moderationStatus ?? row.reason)}</span></>; return href ? <Link key={row.id ?? index} href={href} className="block p-3 hover:bg-sand-50">{content}</Link> : <div key={row.id ?? index} className="p-3">{content}</div>; })}</div> : <p className="mt-2 text-sm text-muted">No linked records.</p>}</section>; }
function ObjectFacts({ title, value }: { title: string; value: unknown }) { if (!value || typeof value !== "object") return null; return <section className="mt-5 border-t border-line pt-5"><h3 className="text-sm font-extrabold text-ink">{title}</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(value as Record<string, unknown>).map(([key, item]) => <div key={key}><dt className="text-[11px] font-bold text-muted">{label(key)}</dt><dd className="mt-1 break-words text-sm text-ink">{typeof item === "object" && item !== null ? JSON.stringify(item) : text(item)}</dd></div>)}</dl></section>; }
function State({ title, value }: { title: string; value: unknown }) { return <div className="min-w-0 bg-sand-50 p-4"><h3 className="text-xs font-extrabold text-ink">{title}</h3><pre className="mt-3 overflow-x-auto whitespace-pre-wrap break-words text-xs leading-6 text-muted">{JSON.stringify(value ?? {}, null, 2)}</pre></div>; }
