import { ZodError } from "zod";
import { apiError, apiSuccess } from "@/lib/api-response";
import { getCurrentProfile, isAccountOperational } from "@/lib/auth/current-profile";
import { verifyCsrf } from "@/lib/security/csrf";
import { checkRateLimit, getClientIp } from "@/lib/security/rate-limiter";
import { ViewingRepository } from "@/repositories/viewing.repository";
import { viewingMutationSchema } from "@/features/viewings/contracts";
type Context = { params: Promise<{ id: string }> };
const privateNoStore = (response: Response) => { response.headers.set("Cache-Control", "private, no-store, max-age=0"); return response; };
export async function GET(_request: Request, context: Context) { try { const profile = await getCurrentProfile(); if (!profile) return apiError("Authentication required", 401); if (!isAccountOperational(profile)) return apiError("Account access unavailable", 403); const { id } = await context.params; const detail = await ViewingRepository.detail(profile, id); if (!detail) return apiError("Viewing not found", 404); return privateNoStore(apiSuccess(detail, "Viewing loaded")); } catch (error) { console.error("[GET /api/viewings/:id]", error); return apiError("Unable to load viewing", 500); } }
export async function PATCH(request: Request, context: Context) { try { const profile = await getCurrentProfile(); if (!profile) return apiError("Authentication required", 401); if (!verifyCsrf(request)) return apiError("Security check failed", 403); if (!isAccountOperational(profile)) return apiError("Account access unavailable", 403); if (!checkRateLimit(getClientIp(request), `viewing-mutation:${profile.id}`, 30, 60 * 60 * 1000).allowed) return apiError("Too many viewing actions. Try again later", 429); const input = viewingMutationSchema.parse(await request.json()); const { id } = await context.params; return apiSuccess(await ViewingRepository.transition(profile, id, input), "Viewing updated"); } catch (error) { if (error instanceof ZodError) return apiError(error.issues[0]?.message ?? "Invalid viewing action", 400); if (error instanceof Error && error.message === "NOT_FOUND") return apiError("Viewing not found", 404); if (error instanceof Error && error.message === "FORBIDDEN") return apiError("Viewing access denied", 403); if (error instanceof Error && ["INVALID_TRANSITION", "CONFLICT", "IDEMPOTENCY_CONFLICT"].includes(error.message)) return apiError("This viewing changed. Refresh before trying again", 409); console.error("[PATCH /api/viewings/:id]", error); return apiError("Unable to update viewing", 500); } }
