import type { Property } from "@/domain/types/property";

export const FALLBACK_PROPERTIES: Property[] = [
  {
    id: "fallback-1",
    title: "Modern 3-Bedroom Duplex",
    type: "Duplex",
    location: "Lekki Phase 1",
    city: "Lagos",
    price: 4500000,
    period: "year",
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    area: 220,
    latitude: 6.4474,
    longitude: 3.4723,
    mappable: true,
    image: "/images/generated/linkconn/property-port-harcourt-duplex.png",
    amenities: ["24/7 Power", "Security", "Parking", "Fitted Kitchen", "POP Ceiling"],
    verified: true,
    featured: true,
    landlord: "Adeyemi Estates",
    rating: 4.9,
    status: "Available",
    description: "A spacious, newly built duplex in a serene Lekki estate with uninterrupted power, ample parking and tight security.",
  },
  {
    id: "fallback-2",
    title: "Bright 2-Bedroom Apartment",
    type: "Apartment",
    location: "Wuse 2",
    city: "Abuja",
    price: 2800000,
    period: "year",
    bedrooms: 2,
    bathrooms: 2,
    toilets: 3,
    area: 140,
    latitude: 9.082,
    longitude: 7.468,
    mappable: true,
    image: "/images/generated/linkconn/property-wuse-kitchen.png",
    amenities: ["24/7 Power", "Borehole Water", "Air Conditioning", "Wifi Ready"],
    verified: true,
    featured: true,
    landlord: "Capital Homes Ltd",
    rating: 4.7,
    status: "Available",
    description: "Tastefully finished 2-bedroom apartment in the heart of Wuse 2, close to malls, banks and restaurants.",
  },
  {
    id: "fallback-3",
    title: "Family Terraced House",
    type: "Duplex",
    location: "Gwarinpa",
    city: "Abuja",
    price: 3200000,
    period: "year",
    bedrooms: 4,
    bathrooms: 4,
    toilets: 5,
    area: 260,
    latitude: 9.109,
    longitude: 7.405,
    mappable: true,
    image: "/images/generated/linkconn/property-gwarinpa-terrace.png",
    amenities: ["Security", "Parking", "Borehole Water", "POP Ceiling"],
    verified: true,
    featured: false,
    landlord: "Greenfield Realty",
    rating: 4.6,
    status: "Available",
    description: "A comfortable terraced home perfect for families, located in a gated Gwarinpa estate with 24-hour security.",
  },
  {
    id: "fallback-4",
    title: "Cozy Studio Apartment",
    type: "Studio",
    location: "Yaba",
    city: "Lagos",
    price: 950000,
    period: "year",
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    area: 45,
    latitude: 6.515,
    longitude: 3.372,
    mappable: true,
    image: "/images/generated/linkconn/property-yaba-studio.png",
    amenities: ["24/7 Power", "Wifi Ready", "Furnished"],
    verified: true,
    featured: false,
    landlord: "Urban Nest",
    rating: 4.5,
    status: "Available",
    description: "Smart, fully furnished studio ideal for young professionals, minutes from the tech hub in Yaba.",
  },
  {
    id: "fallback-5",
    title: "Luxury 5-Bedroom Mansion",
    type: "Mansion",
    location: "Banana Island",
    city: "Lagos",
    price: 25000000,
    period: "year",
    bedrooms: 5,
    bathrooms: 6,
    toilets: 7,
    area: 650,
    latitude: 6.425,
    longitude: 3.43,
    mappable: true,
    image: "/images/generated/linkconn/property-lekki-bedroom.png",
    amenities: ["Swimming Pool", "24/7 Power", "Security", "Parking", "Furnished", "Air Conditioning"],
    verified: true,
    featured: true,
    landlord: "Prestige Properties",
    rating: 5.0,
    status: "Available",
    description: "An exquisite waterfront mansion with private pool, smart-home features and round-the-clock concierge security.",
  },
  {
    id: "fallback-6",
    title: "Affordable Shared Room",
    type: "Shared Apartment",
    location: "Choba",
    city: "Port Harcourt",
    price: 480000,
    period: "year",
    bedrooms: 1,
    bathrooms: 1,
    toilets: 2,
    area: 30,
    latitude: 4.894,
    longitude: 6.917,
    mappable: true,
    image: "/images/generated/linkconn/property-choba-common-room.png",
    amenities: ["Wifi Ready", "Borehole Water", "Security"],
    verified: false,
    featured: false,
    landlord: "Campus Lodgings",
    rating: 4.2,
    status: "Available",
    description: "Budget-friendly shared accommodation close to the University of Port Harcourt, perfect for students.",
  },
];
